### ISSUE TITLE
Homepage: Most Recent Posts section 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#245]
Include a "Most Recent Posts" section of the website. 
![screen shot 2017-10-05 at 3 53 46 pm](https://user-images.githubusercontent.com/16693738/31256134-8544b56c-a9e5-11e7-8848-99b7562d5039.png)

**Comment by kathreenriel** [comment]
This works but needs to illustrate only the most recent 4 events right now it shows 
<img width="1163" alt="screen shot 2017-11-17 at 9 21 23 am" src="https://user-images.githubusercontent.com/16693738/32960203-edded49a-cb78-11e7-8c48-e37699056bc6.png">

**Comment by kathreenriel** [comment]
Also please clarify if this works by location how specific is the location parameter? City? Address?

**Comment by bdolor** [comment]
location parameter is `location_id` in the database, this is as specific as a building, or the place where the event is being held

**Comment by kathreenriel** [comment]
So recent posts may be populated by the same organizer if their events are in different buildings/addresses within the same city?

**Comment by kathreenriel** [comment]
Just checked the two most active Organizers (Options and Westcoast) on the prod. site and 90% of their events are at the same location.

**Comment by kathreenriel** [comment]
I think this could work :)

**Comment by kathreenriel** [comment]
Okay I think this works as expected. Tried multiple postings under various users, similar locations and different locations.

**Comment by paulagaube** [comment]
I tested this, logged in as Bradner Community Place, and found: 
More than one event posted by Bradner Community Place appears on the “Recently Posted” list.
What I noticed on this Recently Posted list is (1) the Events are displayed in Alphabetical order, not by the timestamp of the most recently posted event at the top and (2) events posted all are being held at different locations (3) if an organizer posts an event at a different location, they can appear on the Recently Posted list more than once.
I tried adding new events from one Organizer at the same location, and in that case, only one event was shown at that location on the Recently Posted list. 
But I discovered: 
•	Four events posted by Bradner Community Place all appear under Recently posted, because....
•	All four postings are being held at a unique location. 
Which means that event LOCATION is unique on the Recently Posted list, not unique User.

**Comment by paulagaube** [comment]
Real case scenario: The Richmond CCRR will be posting a three-part event series in January and February 2018, and those events are being held at two different locations over three different days. We are telling Richmond CCRR to create a new event for each day of the series. So the Richmond CCRR will show up on the Recently Posted list twice, because their event series is being held at two different locations on different days.  
Richmond CCRR has indicated that there will be other events like this in the future.

**Comment by paulagaube** [comment]
@kathreenriel Is there anything else you'd like to me test on this one?

**Comment by kathreenriel** [comment]
I think the Richmond CCRR is the exception to the pattern of posted training events. That's all there is to do right now @paulagaube
