### ISSUE TITLE
Lazy-loading CSS

### ISSUE THREAD

**Issue by alex-418** [BCcampus/eypd#273]
Find the best way to lazy load CSS.; Consider using an IntersectionObserver to intelligently determine when to lazy-load css.

**Comment by bdolor** [comment]
this may be something to look into: https://github.com/filamentgroup/loadCSS

**Comment by alexpflores** [comment]
Investigate how to achieve this in WordPress

**Comment by alexpflores** [comment]
While looking for a WordPress specific implementation of this (scarce results, and all are related to images) I stumbled upon [Fetch Injection](https://hackcabin.com/post/managing-async-dependencies-javascript/) and a WordPress implementation of this via a beta plugin [Hyperdrive](https://hackernoon.com/putting-wordpress-into-hyperdrive-4705450dffc2). During my tests, I noticed significant performance improvements, but there are issues with this beta plugin. Definitely something to keep our eye on in the future for a stable release.

**Comment by alexpflores** [comment]
To achieve this, we'd need the following: 

1. A way to automatically identify critical css on a page, and inline that styling while async/deferring the rest so that pages first paint is fast. 
2. A way to Enqueue all of our themes/plugins/external CSS files which  adds the required JS and non JS fallback code. Or find another way to do that dynamically. 

I have not found a single solution that will adequately help us accomplish the above, and doing it manually would not be feasible. It will require a combination of plugins/tools.

**Comment by alexpflores** [comment]
Moving #275, #276, #273 into validating, as the goal of the tasks was to produce knowledge/a way forward. This is me right now: 

![mind_blown](https://user-images.githubusercontent.com/17072191/32860578-e131b28a-ca06-11e7-87af-7ff20c9a866d.gif)

**Comment by kathreenriel** [comment]
I kind of felt this way after reading your summary for #275 :)
