### ISSUE TITLE
Investigate Notifications System

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#320]
This issue is a follow up to #79 and the summary of the investigation  can also be found on https://portal.bccampus.ca/confluence/display/EY/Web+Development%3A+Notifications

Goal: Create a notifications system that alerts users to new content on the EYPD site based on user customizations. 

Specifications outlined by Alex below:

<img width="496" alt="screen shot 2017-11-24 at 9 52 30 am" src="https://user-images.githubusercontent.com/16693738/33224614-3c1d6052-d120-11e7-9088-7fa8e4ba3335.png">

Draft Storyboard
[notifications storyboard.pdf](https://github.com/BCcampus/eypd/files/1502597/notifications.storyboard.pdf)

**Comment by bdolor** [comment]
Just to start some discussion around implementation, it's important to point out that (in terms of out-of-the-box functionality around a notification system) a huge part of buddypress is notifications. It is the most robust offering and as a far as matching the requirements outlined in the storyboard, brings us close without lifting a finger. The unknown is how much we can make it bend to our will. I will be putting some time into exploring how customizable/extensible that notification system is in buddypress.

**Comment by kathreenriel** [comment]
Received this feedback from user testing this morning. Adding a notification to the expiry date of the certification on the MyEYPD page may be connected to the notifications currently being explored.

<img width="610" alt="screen shot 2017-11-30 at 12 43 04 pm" src="https://user-images.githubusercontent.com/16693738/33453953-3a68a61c-d5cc-11e7-9621-9720abf370e0.png">

**Comment by bdolor** [comment]
Currently looking at: 

- https://webdevstudios.com/2015/10/06/buddypress-adding-custom-notifications/

**Comment by bdolor** [comment]
**Summary:** A custom plugin needs to be built in order to meet the requirements outlined above. The main challenges are the multitude of options that a user is given when configuring their notification preferences, and presenting a 'digest' option (daily/weekly/etc) where the assembly and dissemination of content needs to be automated.

**Options Explored:**

1. Existing Newsletter Subscription Plugins (MailPoet/MailChip)
2. Extending BuddyPress Notifications
3. Extending Events Manager Notifications
4. Custom Plugin

- The main limitation with existing plugins is the requirement of users subscribing to 'lists'. Given the options that would be presented to users, a list would need to be created for each location, category, speaker, keyword, etc. Creating hundreds of lists and asking that the user manage subscribing to those lists makes this option untenable. Subscribing to multiple lists also doesn't guarantee that a user won't be presented with duplicate events. 1. a user subscribes to a list, say the 'events in Richmond' list. 2. user also subscribes to a 'events in Child Care Category' list. 3. An event gets created that is both in Richmond and in the Child Care Category. 4. The user gets duplicate emails, from having been subscribed to both lists. 

- BP seems to have a pretty robust notification system, and that seemed like the obvious choice. There are very obvious hooks into the system, for instance, events manager hooks into the BP notification system with 'Bookings'. This is why we have a nice list of 'Events I'm attending'. So, the task then, is about amalgamating a list of events that meet the criteria of user prefs and sending it outside of the system. Current examples seem to be plugins like group email subscriptions https://wordpress.org/plugins/buddypress-group-email-subscription The belonging to a group requirement (a buddypress feature) is similar to the needing to subscribe to a specific list, in that we'd have to create a bunch of groups with no guarantee of overlap not occurring. I'm also unconvinced the immediacy of BP notifications caters to the email digest requirement. 

- Events Manager currently extends BuddyPress Notifications, so when we talk about Extending Events Manager we're really talking about extending BP (see 2 above).

- It appears the way forward is to build our own custom plugin.

The following pseudo-code represents the simplified logic required: 

**IMMEDIATE**
- post is published
- get list of users who opt in for notifications
- loop through user list
- for each user, if preferences match post->data, add user ID/email to notification list
- loop through notification list to send an email

**DAILY/WEEKLY/MONTHLY**
- post is published
- get list of users who opt in for notifications
- loop through user list
- for each user, if preferences match post->data, add post->ID to user's queue
- once a DAY/WEEK/MONTH, loop through each user's queue
- send an email with all Post->ID's/GUID's collected
