### ISSUE TITLE
myEYPD: See which forms can be ajax-ified

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#424]
### Description 

There are a bunch of forms on the myEYPD page. 

**Expected behaviour** 

We'd like to see as many forms move to not requiring the page to re-load.

**Actual behaviour** 

Many PHP based forms require a page load and are tied into out of the box events-manager plugin behaviour.

**Comment by alex-418** [comment]
After mapping it all out, it's clear that every form we would ajax-ifie requires also ajax-ifing other sections that use that data as well. Those elements aren't always on the screen (especially if there's lots of items in the lists).  

**Forms:**
1. Calculate hours form
2. Certificate date expiry form
3. Subscribe to notifications form
4. Past events attended/did not attend form
5. Professional interests form 

**Elements that require the data from above forms**:
1. Certificate info box 
2. Donut
3. Recommended Events

Example:
Toggling the "Attended/Not attended" values via ajax, would also require the following two off-screen items to be recalculated and updated:
1. Fat donut
2. Certificate hours 

Same goes for the relationship between professional interests and recommended events. 

**Recommendation:** 
It will be tough to achieve within time constraints of sprint, and technically challenging. I'm also concerned it would not be obvious to the user what's changed on the page. If we are all thinking the page is becoming too large/complex, then I'd like to suggest instead of making this whole page dynamic, we take a look at achieving the desired results by tabbing out these sections? This would at least solve the problem of having 5 forms on a single page which update related elements the user can't see... @bdolor @kathreenriel @paulagaube @mandily-p Thoughts?!

**Comment by kathreenriel** [comment]
I think further user testing will confirm just how much is "ajaxing"  is required.
