### ISSUE TITLE
myEYPD Page: Upcoming Events

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#475]
Add a registration link (if one is included in the event description) to the listings under Upcoming Events I'm interested in. 
If no registration link exists, display "Contact Organizer to Register" and link back to the event details page with the organizer contact info in view.

![screen shot 2018-06-24 at 9 14 26 pm](https://user-images.githubusercontent.com/20425828/41830124-cb73b650-77f3-11e8-9465-70a40e694e92.png)

**Comment by mandily-p** [comment]
I'd like to see a simple "Register online" link instead of the url.

**Comment by bdolor** [comment]
- `registration link` is the wording if an event organizer has added a link
- `contact organizer` is a link back to the event page.

**Comment by paulagaube** [comment]
Title case please: Registration Link and Contact Organizer

**Comment by kathreenriel** [comment]
@bdolor The delete link  is very close to the Registration Link when the screen is not maximized. On the phone it appears right next to the Registration Link 
 is it possible to shift the Delete link  over a little to the right? 

<img width="558" alt="delete" src="https://user-images.githubusercontent.com/16693738/42004569-32204e76-7a25-11e8-94dc-4c28826af755.png">

**Comment by mandily-p** [comment]
In general it would be good to increase the left/right cell padding so we don't run into this problem in other areas too.

This works and helps keep the left edges aligned with the table headings:

padding: 1em 1em 1em 0;

**Comment by mandily-p** [comment]
The data in the table is self explanatory - I don't think we need the table headers here.

@bdolor I'm also curious to know why you'd like to go with "registration link" and "contact organizer"?
Ideally I'd like to tell the user what to do to register. So "registration link" doesn't have a verb, and "link" is redundant because it is a link. Just as you wouldn't say "checkout button", you don't know need to say "link".
On the "contact organizer" side of things - it would be nice if we could tell the user what they should be contacting the organizer for, which is why I originally included "to register".

I'm open to conversation about this. Let me know your thoughts!

**Comment by bdolor** [comment]
@mandily-p I have no stake in the content game...will defer to @kathreenriel — was merely capturing what was discussed at the planning meeting.

**Comment by paulagaube** [comment]
@mandily-p In our meeting on Monday, we decided to go with "Registration Link" because that is the same text used on the Post an Event form that Organizers use. It may not be perfect, but we chose this to use consistent language on the site (and was not Brad's singular decision). If we change that text on the Post an Event form, let's change it on the Upcoming Events list too. For now, this is consistent. 

![eypd-post-event-form-registration-link](https://user-images.githubusercontent.com/26391359/42010361-280db81a-7a43-11e8-9079-d714b48c0055.png)

Having said that, if we keep the table header row with descriptive text (e.g. "Date/Time" "Upcoming Event" "**Registration Link**", etc.) on the top of the table, then using the actual link to the registration form next to the link to the event listing might make this point moot.  E.g.:

![eypd-post-event-form-upcoming-events](https://user-images.githubusercontent.com/26391359/42010557-176fd5dc-7a44-11e8-8148-869e478b6af5.png)


I think "Contact Organizer" under this heading is self-explanatory.

**Comment by kathreenriel** [comment]
<img width="653" alt="screen shot 2018-06-28 at 2 00 45 pm" src="https://user-images.githubusercontent.com/16693738/42060507-ebcacdd6-7adb-11e8-8c9d-a0e1e60ccef8.png">

**Comment by kathreenriel** [comment]
The external link icon doesn't show up on all the Contact Organizer labels ( on Firefox and Safari) 
and yes....I cleared my cache...several times...ay yaya

**Comment by bdolor** [comment]
There were a few voices in the choir on this one, so could only take a guess as to what the final decision was/is/could be...for now, the expected behaviour is to have an external link icon show up when there is an external link to go to, and for it not to show up if no link was provided (in which case it just links back to the event). In both cases, there is a link and in both cases the wording is 'Contact Organizer'.

**Comment by kathreenriel** [comment]
Oh okay...I get it. Yes, I got to the choir practice late on this one.

**Comment by kathreenriel** [comment]
Will move back to validating

**Comment by paulagaube** [comment]
We were just warming up our vocal chords I think. :)

**Comment by kathreenriel** [comment]
@bdolor btw love the trash can image.

**Comment by kathreenriel** [comment]
<img width="696" alt="notexternallink" src="https://user-images.githubusercontent.com/16693738/42061396-de09b2d6-7ade-11e8-8265-c7ee46fc50e9.png">

**Comment by bdolor** [comment]
as discussed on the phone, this is more than likely a false positive. The value of the registration link for the 'event for everyone' event is `eypd.bccampus.ca`. Since the event lives on the same domain (eypd.bccampus.ca) it presents as an external link with the icon, but takes the user back to the same domain. I believe this is an anomaly and we can safely assume that organizers will not be putting in a registration link that links back to the domain they're working on.
