### ISSUE TITLE
Homepage: Add "Find Events" to the to the top  navigation in the 

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#509]
### Description 

Add a link Find Events to the horizontal navigation in the top right side of the homepage

**Expected behaviour** 

When a user clicks on Find Events the link takes them to https://earlyyearsbc.ca/events/

<img width="582" alt="navigation" src="https://user-images.githubusercontent.com/16693738/43924217-e16838c4-9bd8-11e8-8957-d4868bdb17bc.png">

**Comment by mandily-p** [comment]
Can we just use "Events" instead? Usually navigation is a list of pages, not CTA's. Text like "Find an event" or "Post an Event" are better for buttons.

Ideally, for me the end game navigation looks like this for an organizer. And without manage events for the learner.
![screen shot 2018-08-09 at 2 07 49 pm](https://user-images.githubusercontent.com/20425828/43925959-b09880d2-9bdd-11e8-97ee-c6b71cacab48.png)

**Comment by kathreenriel** [comment]
Where does Manage Events go?

Does  Manage Events mean extra clicks for the Organizer who wishes to post events?

**Comment by paulagaube** [comment]
If we are changing the button/link names, then I would like to see the **myEYPD** link stay on the far right and have any buttons/links that are going to change (or be removed for Learners) get added to the left, so that myEYPD is in a constant/static position.  
e.g.  >>  "Find Events"  "Manage Events" "myEYPD"
(or whatever the final text is)

**Comment by kathreenriel** [comment]
Eventually I think a "Manage Events" section could replace Post An Event and Edit An Event. But we need a storyboard for this and consider that this link would only appear for Organizers not Learners. 
@paulagaube Yes I agree that myEYPD should always be in the same location.

**Comment by mandily-p** [comment]
@kathreenriel by storyboard do you mean a mockup or flow? I've only ever completed storyboards for animation or video projects. 

WRT the position of myEYPD - Ideally it's the first link in the navigation (other than home) because users read left to right and we'd like them to treat their dashboard as their home base for everything else on the site. So it should be the first thing they see/read.

Having it in the "same location" based on the right side of the screen is only useful in the case of a UI element that's widely used across the web (like a shopping cart) or when user that would see multiple variations of the site navigation regularly. I think in our case a user is either a learner or an organizer and would only ever see that switch once at most if they upgrade from learner to organizer.

Just my two cents. I just wanted to give you the rationale behind my thinking. I'm fine with whatever your preference is :)

**Comment by mandily-p** [comment]
It's my understanding that the menu is considered content and therefore @paulagaube or @kathreenriel would have edited it in the past. When I look at the admin vs the front end, the menu items don't align. 

Can one of you tell me how and why it's done outside of the menu feature in Wordpress?

![screen shot 2018-08-20 at 2 07 08 pm](https://user-images.githubusercontent.com/20425828/44366712-64e17100-a482-11e8-8cb4-7711b58cf738.png)

**Comment by alex-418** [comment]
@mandily-p The answer is pop-overs, and different menus for logged-in vs logged out users. So that means this would be a development task instead.

**Comment by mandily-p** [comment]
Ah. I never considered that! Thanks for heads up @alex-418. I could do a copy pasta for another menu item in the php file, but I don't know if there's any unit tests for the menu and if there are I can't write them. So I'll leave this up to you. :)

**Comment by alex-418** [comment]
@mandily-p no prob! For reference here's how the menu's generated, i'll be updating this function to make this change. https://github.com/BCcampus/eypd/blob/851e9780772ea3517e637407991aec9afbc9a330/functions.php#L793

(p.s. github tasks are self-assigned)

**Comment by mandily-p** [comment]
Sweet! thanks for the teaching moment!

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/commit/8bbb26c79926a7685822c64070c9beaae21c0165

**Comment by kathreenriel** [comment]
Checked in Firefox, Safari, Chrome
