### ISSUE TITLE
Add OpenGraph tag for images posted on social media

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/eypd#512]
### Description 
Now that we're posting on social media, it would be a good idea to make sure the previews that appear with the links that we post include the best representation of the content underneath that link. *I think* we do this with OpenGraph tags in our pages. Full disclosure that I don't fully understand the tech behind this or if it could be completed with a WP plugin.

**Expected behaviour** 
The default image should be the site logo. 
The default text should be, "EYPD aims to support the B.C. Early Years sector by hosting, developing and evaluating a professional development web portal."

**Actual behaviour** 
When posting the home page link of the site, an image of the toolkit for domestic violence appears with a description of Appetite to Play.

![screen shot 2018-08-14 at 11 24 58 am](https://user-images.githubusercontent.com/20425828/44110725-53bac60a-9fb5-11e8-875f-56ed3382439e.png)

**Comment by mandily-p** [comment]
https://developers.facebook.com/docs/sharing/opengraph/

**Comment by alex-418** [comment]
These changes to the markup will requires pushing to production to test.

**Comment by alex-418** [comment]
@mandily-p just realized our cert http://eypd.bccampus.ca is actually public facing, we can test FB links there. I've partially completed this via https://github.com/BCcampus/eypd/commit/8ca076f90f09ed9ba3a1c1b7c1b417e04b204797 by adding the Open Graph tag to the EYPD logo image. Can you please test by putting linking to http://eypd.bccampus.ca to see if that grabs the correct image? Right now, since i've added that, i expect all pages will have the EYPD logo chosen as the image (can you please confirm this.)

The ones left to do are for pages, and posts. I can add this tag to the featured images for both pages/posts... **BUT** problem is that event images are not actually Featured images in event posts. They are inserted inline. No easy way to do this, but I'm thinking: 1.) Need a regex to detect if the post content has an image, extract the URL, store it. 2.) Add a conditional in the header to check if it's a post (of type event) and if an image exists, then produce the open graph tag with the correct url of that image... to be continued

**Comment by alex-418** [comment]
@mandily-p Please confirm the image is consistent whenever a link to the eypd.bccampus.ca website is posted to FB.

**Comment by mandily-p** [comment]
It looks like the default image is actually the province's logo

![screen shot 2018-08-21 at 9 12 08 am](https://user-images.githubusercontent.com/20425828/44414358-6b272a00-a522-11e8-973f-7b16d2589344.png)

**Comment by alex-418** [comment]
@mandily-p @kathreenriel  Open Graph doesn't support SVG images, explains why it's not showing the correct image. Can I get an EYPD logo image in .png format please?

**Comment by kathreenriel** [comment]
@mandily-p would you format and post a png image here?

**Comment by mandily-p** [comment]
The EYPD logo is png. The hand is raster, there is no vector version.

**Comment by alex-418** [comment]
@mandily-p The theme uses SVG for the main logo... the only pngs are really small. I'm looking for a eypd-logo-final.png instead of svg. Do you see that as a png somewhere else in the theme or website? Here's the link to the SVG i'm talking about https://earlyyearsbc.ca/wp-content/themes/early-years/dist/images/eypd-logo-final.svg

Here's the theme image assets: 
![assets](https://user-images.githubusercontent.com/17072191/44424447-fc57ca00-a53d-11e8-9669-7b08b7b4e7b9.png)

**Comment by mandily-p** [comment]
I made one of each for you. The hand technically isn't large enough, but I scaled it up so we could use the whole image at 200px square.

![eypd-logo-bc](https://user-images.githubusercontent.com/20425828/44425230-1db9b580-a540-11e8-88de-300bff1443f8.png)
![eypd-logo](https://user-images.githubusercontent.com/20425828/44425231-1e524c00-a540-11e8-8760-5bc8469b028c.png)

**Comment by mandily-p** [comment]
@alex-418 Are you investigating the preview text with this ticket too or should I make a new issue?

**Comment by alex-418** [comment]
@mandily-p I can do that here, working on it

**Comment by alex-418** [comment]
@mandily-p Image, description, and image alt text added. Let me know if that works well?! 
Happy to modify the copy if you can can provide... (it's limited to about 2 sentences). 

Here's what it looks like: 
![opengraph](https://user-images.githubusercontent.com/17072191/44427379-3fb63680-a546-11e8-87ee-9e546ae6df82.png)

**Comment by kathreenriel** [comment]
@mandily-p would you please validate this?

**Comment by kathreenriel** [comment]
When I FB share an event on the event description page on EYPD this is what appears after clicking FB icon at the bottom of the page. 
<img width="672" alt="screen shot 2018-08-21 at 1 52 56 pm" src="https://user-images.githubusercontent.com/16693738/44428569-9ffaa780-a549-11e8-888b-7aab455529a9.png">

**Comment by alex-418** [comment]
@kathreenriel Can you please try it in this tool and screen capture the result here? https://developers.facebook.com/tools/debug/

**Comment by mandily-p** [comment]
@alex-418 Can you edit the description so that training only has one "n" please. Otherwise it reads ok to me. @kathreenriel Are you ok with the description?

**Comment by mandily-p** [comment]
Sharing the home page:
![screen shot 2018-08-21 at 3 34 46 pm](https://user-images.githubusercontent.com/20425828/44432659-cc1d2500-a557-11e8-89a8-4af4c9e9f90d.png)

And as Kathreen, I see the same when I post an event.

**Comment by mandily-p** [comment]
And the plot thickens....

It looks like WP actually shrinks down the banner images on the events so that they're too small for fb to recognize. 

@alex-418 Is there a way to edit the theme so that all new photos being uploaded going forward will be an appropriate size for sharing?

![screen shot 2018-08-21 at 3 54 33 pm](https://user-images.githubusercontent.com/20425828/44433344-bf4e0080-a55a-11e8-8323-9658cd24e9e4.png)

**Comment by mandily-p** [comment]
@kathreenriel  About halfway through the thread: https://github.com/BCcampus/eypd/issues/512#issuecomment-414811704

**Comment by alex-418** [comment]
@kathreenriel @mandily-p  Resolved via https://github.com/BCcampus/eypd/commit/fc903ee4615edfe1a65b6e016fa78cbe9d77770b ... three lines of code turned into 2 functions with 60 lines of code... I had to add some logic to provide different information if it was a page vs post, and added 6 total tags. I've also added some logic so you'd have more control of what shows up in these FB links. Here's a breakdown of how this looks, and works: 

 
![debug](https://user-images.githubusercontent.com/17072191/44484426-97b27300-a602-11e8-9464-6241c23ff967.png)

**Description text:**
As highlighted in red text, i've made it so it pulls the tag description from the excerpt. If none exists, then it uses the websites default description (This is set and controlled in WordPress Dashboard). Currently there are no excerpts with events, or pages, so the site description will show up in it's place. Excerpts can be manually created in the dashboard editor, but since we don't give them access to this I think a better route to get accurate descriptions would be to automate the creation of excerpts for events. I have created a separate issue for that: https://github.com/BCcampus/eypd/issues/524

**Images:** 
Will use the "Featured image" of a post or page. We currently don't make use of this, so the default website logo image is used. If we want to pull the event image, we'd have to move to using featured image on events, which requires giving them access to the back-end editor. Please create a new issue for this if this is desired.

**Comment by kathreenriel** [comment]
Given that it will Amanda and I will publishing all of the posts in FB it sounds like we could ensure that we manually create an excerpt if we wish to post a specific event description page. For images we can manually create a feature image as well for specific events. 

Way to go @alex-418 thanks for going down this long rabbit hole

**Comment by mandily-p** [comment]
@alex-418 What would the text be here on prod?

![screen shot 2018-08-23 at 9 24 34 am](https://user-images.githubusercontent.com/20425828/44538571-92166500-a6b6-11e8-9807-f6e69a7d3023.png)

**Comment by alex-418** [comment]
@mandily-p Please see https://github.com/BCcampus/eypd/issues/512#issuecomment-415145404

**Comment by alex-418** [comment]
@mandily-p  This is the prod description, and where you could change it:
![prod_description](https://user-images.githubusercontent.com/17072191/44539041-fab21180-a6b7-11e8-965a-ae3677a9bb78.png)

**Comment by mandily-p** [comment]
Better question: How do I find the prod site description?

**Comment by mandily-p** [comment]
You beat me to it. Thanks @alex-418 !

**Comment by mandily-p** [comment]
This works and looks good to me! 👍 

I'll let Kathreen decide if we need to update the prod text or can leave it as is.

**Comment by kathreenriel** [comment]
Okay, here's what I wrote on the production server tagline ( the cert server has a different purpose)  

"Find professional development in the early years sector"

@mandily-p @paulagaube open to edits and suggestions

**Comment by paulagaube** [comment]
I tested adding https://eypd.bccampus.ca to a Facebook post and the post looks good with the EYPD hand image. 

I know this hasn't been done yet, but I also tried to add https://earlyyearsbc.ca and there is no image, only the URL for the website. Nothing damaging there. :)
