### ISSUE TITLE
Notifications plugin not sending future training events

### ISSUE THREAD

**Issue by kathreenriel** [BCcampus/eypd#555]
Description 

When I sent a test email from the  WP notifications plugin to three different users the training events that are sent are the events that occurred in the past as well as one event sending the user to a 404 page.  

Expected behaviour
Training events listed in the email notification are events happening in the future based on the users selected interests. 

[What you expect/want to happen]
Recipients receive notifications based on upcoming training events that reflect their professional interests as indicated on the sign up page. 

**Actual behaviour** 
Training events are events that happened in the past. 

### Steps to reproduce the problem
Send a test email to view the problem. 

<img width="615" alt="notifications" src="https://user-images.githubusercontent.com/16693738/46828270-adfdc500-cd4f-11e8-9b73-9d2d0ddce8d9.png">

**Comment by bdolor** [comment]
Should be resolved so that test emails are now displaying updated/recent events. 

There are two processes, _build_ and _notify_ that are triggered by various things and out of an abundance of caution, **not** triggered by various things. The last time it _'built'_ the most recent events was in April, so was email testing was displaying those not-so-recent recent April events. Prior to the actual _'notify'_ event where it runs through the list of subscribers, a _'build'_ event is triggered, so that it gets the latest right before the moment it sends. In other words it would have worked itself out. From a testing perspective though, I can see how 'forcing a build' would be a very useful feature request. I encourage you to add an issue to https://github.com/bccampus/custom-wp-notify/issues to capture that.

**Comment by kathreenriel** [comment]
Great! Just tested this again and it shows all future events. I will activate this next Tuesday.

**Comment by kathreenriel** [comment]
@bdolor Thank you!
