### ISSUE TITLE
Export Users label order 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/eypd#626]
### Description 

A bug was introduced in the custom-wp-notify plugin

**Expected behaviour** 

when exporting user data, csv headers need to match the data in the column

**Actual behaviour** 

two of the labels are in the wrong order

### Steps to reproduce the problem

export the users and look to the last two columns.

**Comment by alex-418** [comment]
Completed via https://github.com/BCcampus/eypd/commit/094b0cd71b16425c1d262e35f618827f4f7c8f60

Additionally updated the Readme with clarification/instructions on when/how BP extended profile data is exported https://github.com/BCcampus/excel-export/pull/27

**Comment by paulagaube** [comment]
@alex-418 @kathreenriel 
Tested and can confirm that the "Name of your place of Work" and "City/Town" column labels are now on the appropriate column heading. 

1. Dashboard > Tools > Excel Export > Export Users
2. Click checkbox "Include personally identifiable information in export"
3. Click button "Export Users"
4. Excel spreadsheet is downloaded: "Users.xlsx" 

There may be other refinements we want to this report, such as removing the columns "URL", "User Level", and "User Status". Some time ago, Kathreen and I also talked about whether there would be a benefit to include "Nickname" instead of (or as well as) the "Display Name". To be determined.  Would these things be easily possible? That would be a separate ticket.

I'd call this issue Done.
