### ISSUE TITLE
Spam and nonsense emails being submitted through Contact Form 7

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#638]
### Description 

Spam and nonsense emails are being sent to the EYPD email address (earlyyears@bccampus.ca) through the contact form we are using at https://earlyyearsbc.ca/contact-us/

User story: 
As an Early Years administrator who responds to legitimate emails that are sent to the earlyyears mailbox
I want the spam emails to stop 
So that I don't have to read them and manually mark them as spam.

This issue also applies to any BCcampus website that uses the Contact Form 7 (e.g., bccampus.ca, open.bccampus.ca and tlpd.bccampus.ca). There is a captcha on the BCcampus.ca form, but spam is still getting through that captcha. (See issue https://github.com/BCcampus/bcc-sage/issues/300 "Contact form captcha not strong enough")

I'd like to make all the contact forms across the sites as consistent and as spam-free as possible. Ideally the solution used on this site could be replicated on our other sites.  

**Expected behaviour** 

No spam gets through the contact form. 

**Actual behaviour** 

Spam is getting sent through the form and delivered to the emailbox. 

### Steps to reproduce the problem
1. Go to: https://earlyyearsbc.ca/contact-us/
2. Fill in the form and submit it
3. An email is sent to the earlyyears@bccampus.ca email account and added to the Contact Form DB

### System Information

- EYPD: Version 1.1.0
- WordPress: 5.0.3

**Comment by alex-418** [comment]
@paulagaube Can you confirm that you are not receiving any spam from [this contact form](https://solr.bccampus.ca/wp/register/)? If that anti-spam solution is working well, then I can look into using that same solution for EYPD.

**Comment by paulagaube** [comment]
@alex-418 @bdolor I submitted a test through that SOLR form and I see the captcha with the images. I'm not a huge fan of those image ones, but it does seem to work. 

However, the submitted form goes to Brad, so I've asked him if he gets much spam through that. (I haven't seen any, but can't confirm as I don't get the messages sent through that form!)

**Comment by alex-418** [comment]
@paulagaube There's a solution [on cert](https://eypd.bccampus.ca/contact-us/) now that should be equally as effective as what is on SOLR with the advantage of not requiring user input. [recaptchav3](https://developers.google.com/recaptcha/docs/v3) 

That being said, It wasn't my first choice because it requires we include links to Google's privacy/terms pages. It uses a lot of different factors to give a score to determine if they are a bot or not, using traffic data. So while it's very effective, it does open up the door to concerns about if we're okay with that or not (similar to how google maps data is being used). But it seems to be the most effective way of preventing spam, since our other solution seems to be failing. 

It also requires a gmail account, currently using my personal so would like to get that into a BCcampus owned gmail account if we decide to move forward with that solution. 

@kathreenriel Please let me know your thoughts on using Google services/solutions, and if you're comfortable with that. Thank you.

**Comment by kathreenriel** [comment]
Reviewed the EYPD PIA form and we have not identified using a third-party program and possible mitigation strategies. Given that this spam issue affects more than this project I think there needs to be a better articulated strategy on how to deal with the spam on more than just the EYPD site.

**Comment by kathreenriel** [comment]
Moving this back into the product backlog

**Comment by paulagaube** [comment]
Thanks, @alex-418 for exploring this spam/captcha issue! We will continue to monitor how much spam we get. May it disappear forever.

**Comment by kathreenriel** [comment]
@alex-418 Just clarifying my previous comment. I think **BCcampus** needs to articulate a policy on how to deal with the SPAM on several sites. Thank you for your investigation @alex-418 I'm escalating this to Dave and Brian since it involves privacy and several websites.

**Comment by kkilbey** [comment]
I recently activated the Honeypot plugin on EYPD, and this has significantly reduced the amount of spam we receive through the contact form.

We noticed that the Honeypot is especially effective with this inline CSS configuration:
[honeypot Email move-inline-css:true]

I have also installed/configured this plugin on other BCcampus sites.

**Comment by paulagaube** [comment]
The Honeypot plugin appears to be working as expected. 
Looking through the spam received and saved through the earlyyearsbc.ca contact form, this now appears to be at a manageable level.
Here are number of spam messages currently in our Junk folder:
December 2018: 1
February 2019: 2
March 2019: 1
April 2019: 8
May 2019 (as of May 9th): 1

@kathreenriel @alex-418 I think we can close this ticket.
