### ISSUE TITLE
Update "Suggest an Event" Contact form text on bottom of myEYPD page

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#642]
### Description 

On the bottom of the myEYPD page (on Cert), there is a "Send Suggestion" button and text entry field where logged-in users can enter a suggestion and send a message to us. That email gets directed through the Contact Form 7 to earlyyears@bccampus.ca.

The text above the "Send Suggestion" button is confusing and needs clarifying. 

This is first a non-dev task to clarify the language, then it may be a dev task to replace the language.

**Expected behaviour** 
Replace the text above the submit button with this (to be reviewed with @kathreenriel first):

"What are your interests? Is there another type of training event you'd like to attend? Suggestions will be shared with event organizers."

**Actual behaviour** 

Go to myEYPD page for user: https://eypd.bccampus.ca/members/<username>/events/

At the bottom of the page, the text says:

"Don't see what you're looking for? Make a suggestion. If there's enough interest and workshop facilitators available, we'll update our calendar with new events."

I already updated the placeholder text to say "Suggest a training event" on the Contact Form 7 plugin
Dashboard > Contact > Contact Forms > Form

### System Information

- EYPD: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by mandily-p** [comment]
To play devil's advocate - if you don't have any evidence of users having trouble understanding this, you'll fall into the trap of changing things for the sake of change and busywork, instead of allocating resources to where they could be most effective. 

I can do some guerrilla user testing on this easily enough if you'd like. All that needs to be done is to print out the bottom section of the page and then show it around to people and ask them if they know what to do with the field, and what clicking the button will do.

**Comment by paulagaube** [comment]
@mandily-p  There are two issues here: 

1. The suggestion form is not currently on PROD. My question in the standup meeting yesterday was do we want it to be on PROD? If the answer to this is YES, (@kathreenriel 's call), 
Then,
2. The text needs to be updated to be factually correct, because WE are not going to offer workshops. We have nothing to do with facilitators or adding events. The website is a portal, a referatory, a collection of events that are hosted by Organizers, not the website and not "us". Organizers own events and we own the portal (for now). So the language has to reflect that and not over-promise.

I don't understand how it would take a developer more than a few minutes to update the text line if we decide to change it? What am I missing? 

Here is the current text, which is factually incorrect: 
"Don't see what you're looking for? Make a suggestion. If there's enough interest and workshop facilitators available, we'll update our calendar with new events."

This is my suggested text, which is open for comments:
"What are your interests? Is there another type of training event you'd like to attend? Suggestions will be shared with event organizers."

I don't see the point in poling users if they understand what the "Suggest" button does if the messaging is wrong.

**Comment by kkilbey** [comment]
Just to chime in, I agree that the messaging isn't quite accurate. It sounds like we're promising to initiate these suggestions rather than pass them along to workshop organizers. I think the functionality of the field will be clear to users once it's on Prod, though.

**Comment by kathreenriel** [comment]
Reviewing my notes from this timeline of discussions we decided to leave the suggestion field out of the bottom of the page because the user cannot determine if they can't see what they are looking for without clicking on "Recommend Events". The Suggestion Field belongs on the results page that appears after Recommend Events. Also the suggest a training event has been included in the contact form.
