### ISSUE TITLE
Clarify how plugin Custom WP Notify works so we can document its features

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#681]
**Is your feature request related to a problem? Please describe.**
Kelsey and I were testing the Custom WP Notify plugin on Cert eypd.bccampus.ca and found we did not get the results we expected when the plugin was activated.* This could be partly user-error or due to a difference in parity with Prod/Cert/Dev, (issue #677) or a misunderstanding of how the plugin works (i.e., is there a Cron Job that needs to run before we can activate the plugin?) 
*We will add some notes on our test results below for increased context. Related to issue #668 

**Describe the solution you'd like**
We would like to have (or be able to create) clear and concise instructions on how to use the Custom WP Notify plugin so that we can use the plugin to send custom emails to users. If we are passing this site to another party, we need to document its proper usage in the Administrators Guide we are creating.

**Describe alternatives you've considered**
Not using the plugin. Asking for the user/professional interests and upcoming events to be exported to a CSV file so we can use Mail Chimp to send custom emails instead. (If this is even possible or practical.)

**Additional context**
As an EYPD Administrator,
I would like to be able to activate the Custom WP Notify plug in Production
So that I can confidently send custom emails to all users so they can find newly posted events, and events that are relevant to their interest area, in a scheduled email.

**Comment by kkilbey** [comment]
Notes from testing email notifications:
- The emails we received contained past events
- The notification emails were set to delay by one hour, but they were automatically sent only a few minutes after notifications were enabled
- Paula adjusted the subscription settings so that Amanda H. and Alex would not receive notifications while we were testing, but Amanda still received an email
- Related to subscription settings: I have three accounts set to receive email notifications (checked box on MyEYPD page that says "Get emails when new training opportunities are added"). However, only one of these accounts received the test email. In the back end, one of these accounts does not appear at all on the subscription management page, in either the subscribed or not subscribed list.

**Comment by dshaykewich** [comment]
Strikes me that this plugin:
- is unreliable
- is not being actively used

I suggest we disable it.
