### ISSUE TITLE
Change one line of text on the Post an Event page

### ISSUE THREAD

**Issue by paulagaube** [BCcampus/eypd#700]
**Is your feature request related to a problem? Please describe.**
See the text under the Heading "Post an Event" on this page: https://earlyyearsbc.ca/post-event/
Long message:
"This form is to be completed in order to post events on this web portal. To add your event, fill in the fields below. Fields marked with an * are mandatory. If you have multiple events to post please contact earlyyears[at]bccampus.ca for assistance."

The text inaccurately tells Organizers to email us for assistance when they don't need our help to post multiple events. (And the text is wordy!) We have received multiple requests for assistance, and this is a time waster for us and the Organizers.

**Describe the solution you'd like**
Shorten the message by removing the first and last sentences on the descriptive text.
Shortened message:
"To add your event, fill in the fields below. Fields marked with an * are mandatory."

**Describe alternatives you've considered**
The FAQs have been updated to include information on how to duplicate an event. We may add another FAQ about how to add recurring events, but smart users can figure out how to do this for themselves. Organizers are definitely not required to ask us for assistance to add multiple events.

**Additional context**

As an Organizer, 
I would like to know that I can add multiple events without asking for assistance
So that I can add my events quickly in the time I have available.

As a member of the Early Years support team,
I would like people to stop asking me how to add multiple events
So that I can use my time to do other things.

**Comment by alex-418** [comment]
Completed via https://github.com/bccampus/eypd/commit/bd6958d47c234417b058970f408c06ea802d7b70 please allow ~5 minutes for the changes to make it over to production.

**Comment by paulagaube** [comment]
Thank you, @alex-418 I've confirmed the change is in Prod and it looks great! 👍

**Comment by dshaykewich** [comment]
@alex-418 , when you have a chance, could you please also make the change on cert so that we keep parity between environments?  :-)

**Comment by alex-418** [comment]
@dshaykewich What preference for cadence do you have for parity on this project? 

I ask because my current plan is to ensure the previous steps taken in https://github.com/BCcampus/eypd/issues/677 are repeated before the next sprint to maintain true parity. The reason behind this is to try an adhere to the dev/prod parity principle in twelve-factor: "all environments should be as similar as possible". Which includes backing services (database: where the settings are for all plugins/themes are etc). This way I'd have great confidence that they are as similar as possible, not worrying about the changes that did/did not make it over. Ideally, this would be automated. Either using our CD strategy with Jenkins, or containers. But for now it takes me about 15 minutes to do manually. 

That being said, if you'd prefer that every single change make it over right away, because there's testing going on right now or just because parity, then I'm also happy to run that build which includes only the codebase parity.

**Comment by dshaykewich** [comment]
@paulagaube noticed that the changes had not been 'tested' in cert, before promoting to prod.

@alex-418 , following the steps in #677 for future sprints sounds good.  My goal is to ensure we do not devolve into divergent sites again.
